modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
credits="Seed maker sound by le_abbaye_Noirlac on freesound.org"
[[mods]]
    modId="horticulture"
    version="${mod_version}"
    displayName="Horticulture"
    authors="joshiejack"
    description='''Crops and Trees!'''
[[dependencies.horticulture]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.horticulture]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.horticulture]]
    modId="penguinlib"
    mandatory=true
    versionRange="${penguinlib_range}"
    ordering="NONE"
    side="BOTH"